name: Keep Repository Alive

on:
  schedule:
    - cron: '0 0 1 * *'     # 每月1日 UTC 0点执行
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: echo "Keeping the repo active"
